### ISSUE TITLE
duplicated p tags in media description after save

### ISSUE THREAD

**Issue by FelixSchwarz** [mediadrop/mediadrop#216]
The bleach html cleaning (see #205 ) introduced a new regression if "p wrapping" of the description text is enabled: Each time the media item is saved the code will add a new `<p>...</p>` so after a couple of saves we have many extra `<p>` tags.

Reported as part of #215

**Comment by FelixSchwarz** [comment]
I ported Donna's changes (dewhisna@5e15f2885d9633182c41a5e89f6a0692d9ababac , dewhisna@e20ca9461bcb1264a47f9381f9159b1cf1e2b917 ) to the latest git master:

* https://bitbucket.org/schwarzeu/mediadrop-work-in-progress/commits/7065c0f274a044cd86ba4db58f91c8419e6d8e65?at=bleach-p-wrap
* https://bitbucket.org/schwarzeu/mediadrop-work-in-progress/commits/e6cdceefbbd6cabbdba52f820c2d82acc5d3584a?at=bleach-p-wrap

@dewhisna If you're fine with my ported commits referenced above I can commit them.

I think your fix is good enough especially as you re-added unit tests so we can always refactor it later. The only thing I need to check is why a single `\n` is not mapped to `<br>`.

**Comment by dewhisna** [comment]
Those look OK to me as long as you are happy with my hack for the `<p>` tags.  I don't really like my solution since it doesn't find existing p-tags that have attributes or something other than a pure set of `<p>` tags.  It really needs to be properly xhtml parsed.  I went with it in my 'fix' because it was quick and simple and the code was already adding the tags in that explicit form so it would at least keep it from continually adding them each time through the editor even if you end up with one set of extra tags around cut-and-pasted text.

As for the single `\n` not mapping to the `<br>`, with me being new to this project, I thought perhaps you guys had done that intentionally.  I actually liked that change because it handles the case of the user doing a copy-and-paste from a source (like an email client) that has already done line wraps using newlines.

In those cases, you'd want it to either leave the single `\n` characters or convert them to spaces and only hard-break the double `\n` characters.  Otherwise you get funky line breaking going on from such text.  So I was liking that change, as pressing enter a couple of times to intentionally create a break is easier than deleting extra `\n` characters when copy-pasting from a source that's been line-wrapped, especially for non-programmer users who don't tend to think about white-space characters.

I also tweaked the tests to verify it that way, thinking that it was done intentionally on the 'master' development branch rather than being a regression.  And I *think* it actually round-trips correctly.  But I'm open for whichever way the group wants to go with it, though my vote is to leave single `\n` as-is.

I've been also debating if something should be put in place for detecting `<div>` tags surrounding the text to possibly treat it as being part of 'p_wrap' in clean_xhtml().  This again comes from cut-and-pasted text, but from an html/xhtml type source that may be using `<div>` tags instead of `<p>` tags for paragraphs, since it's a little more flexible with css usage.

But, I'm on the fence on this one, because it shouldn't hurt anything to add an extra `<p>` block around the whole thing.

**Comment by FelixSchwarz** [comment]
Fix committed in 92b6680505ec71c1b6d22e39c09c7bf9869e15ac and c90117b56ac0f7e9362116f02d2424963111dc20

> I don't really like my solution since it doesn't find existing p-tags that have attributes or something other than a pure set of `<p>` tags. It really needs to be properly xhtml parsed.

This would be the "full" solution solving all possible edge cases and I'd be happy to merge such code if it existed. Until then I think the most important aspect is that users can use the media admin in a "normal" way without duplicated `<p>` tags (probably we could even get away with checking for something like `<p\s*`).

> As for the single `\n` not mapping to the `<br>`, with me being new to this project, I thought perhaps you guys had done that intentionally.  I actually liked that change because it handles the case of the user doing a copy-and-paste from a source (like an email client) that has already done line wraps using newlines.

That's what I figured as well (the xhtml normalization was submitted by SimpleStation back in the day and I never looked into it too much until now) and I agree that it seems to be quite useful. Maybe adding a comment to one of the existing unit tests would be good.

> I've been also debating if something should be put in place for detecting `<div>` tags surrounding the text to possibly treat it as being part of 'p_wrap' in clean_xhtml().  This again comes from cut-and-pasted text, but from an html/xhtml type source that may be using `<div>` tags instead of `<p>` tags for paragraphs, since it's a little more flexible with css usage.
>
> But, I'm on the fence on this one, because it shouldn't hurt anything to add an extra `<p>` block around the whole thing.

Well, if you like to spend your time  in doing it this would be a nice addition but I know many more features which could be added which bring much more user value so I'm not doing this...
