### ISSUE TITLE
plain text description broken after adding bleach for xhtml cleaning

### ISSUE THREAD

**Issue by FelixSchwarz** [mediadrop/mediadrop#217]
The bleach html cleaning (see #205 ) introduced a new regression so that the automatic "plain text" generation (`Media.description_plain`) won't work anymore. Instead it escapes all HTML markup which makes the plain text "unreadable".

**Comment by dewhisna** [comment]
Yeah, I was actually just starting to look into this issue of "plain text" description generation.  I think I know where the bleach changes broke it, but haven't yet found the best fix.  At present, I've been manually editing my database to fix it after editing a new media item, but that's getting old.
I am also planning to add some tests for it too, as there presently isn't any test for checking that path.

**Comment by FelixSchwarz** [comment]
I added a basic unit test in 19b11a8fada5f67e36af90fc68b8fc43e2a23b8b (currently skipped to prevent failing builds)

**Comment by dewhisna** [comment]
Cool, thanks!  I got half of #217 fixed in my v0.10.3_with_bleach branch with @e4d8264ed6a0f365896497faab25586690cfaf2c.  At least one problem is that all of the changes for bleach made entities_to_unicode() do exactly the opposite thing that it should.  Instead of turning things like `&amp;` into `&`, it was turning `&` into `&amp;`, etc.

I fixed that and improved the scrubbing a bit for that function to help fight code injection, and added a test case for it to verify it (I think you'll like this change).  This has really helped the "plain text" description issue #217, but some xhtml is still getting through elsewhere.  I've found a few things with the strip_xhtml() function, but I'm still chasing that rabbit because it also seems related to how bleach is scrubbing the initial rich description too before transformation to the plain version.

**Comment by dewhisna** [comment]
OK...  I think I have it working now.  Took me a bit to wrap my head around bleach and realize that a call to `clean()` doesn't remove all xhtml tags.  It only sanitizes them from the evil tags.  You have to explicitly say you want no tags or attributes.  If you merge bdfb997280e8acb09c599aa02facab48cf677312 and the previous e4d8264ed6a0f365896497faab25586690cfaf2c (you will need both commits), I think you'll find that this fixes the 'plain text' issue and you can close #217.

Cheers!

**Comment by rbu** [comment]
Commits are in and the test is no longer skipped, closing this. @dewhisna, thanks a lot for the work!
