### ISSUE TITLE
FastCGI issue, mediadrop.fcgi Fails to remain running

### ISSUE THREAD

**Issue by jd4rider** [mediadrop/mediadrop#243]
When I execute the mediadrop.fcgi file from command line it puts out some beautiful html.  When I try to hit it from http://hostip/my_media in the browser it gives 500 error and apache error logs read as follows:

[Sat Jan 06 09:08:29.383970 2018] [:warn] [pid 16098:tid 139804786558848] FastCGI: (dynamic) server "/var/www/html/my_media/mediadrop.fcgi" has failed to remain running for 30 seconds given 3 attempts, its restart interval has been backed off to 600 seconds

**Comment by jd4rider** [comment]
I think it's a permissions issue, but I can't figure out how to correct it.

**Comment by FelixSchwarz** [comment]
I think this error message occurs if you try to run a CGI script with fcgi. If you run the code from the command line does the process exit after returning the HTML or do you have to use Ctrl+C?

Can you check that your mediadrop.fcgi file contains:

    from flup.server.fcgi import WSGIServer
    WSGIServer(app).run()

Did you install flup?

Also check your mediadrop logs for more hints (e.g. the file referenced by [handler_logfile] in production.ini).

**Comment by jd4rider** [comment]
Flip is installed and I get HTML back on the command line.  I followed the instructions from MediaDrop.video.

I also tried the WSGI method and get (13)permission denied.

It’s installed on root in Ubuntu, should I move the application to another folder and where do you propose? Can I just mv recursively that folder MediaDrop is in so I don’t lose the application as it is?

**Comment by dewhisna** [comment]
Make sure your 'data' folder is read/writeable by the 'www-data' user/group under which Apache is running, as that's the user/group for Apache (which doesn't run as root).  The main MediaDrop code itself can stay owned by root, but the data folder has to be accessible by Apache.  It's probably working on the command-line because the user/group you're running under can read/write the data folder, but Apache can't.

**Comment by jd4rider** [comment]
I ran chown www-data:www-data the data folder and restarted apache and it
didn't work.  I ran chown www-data:www-data mediadrop -R up one level,
restarted the server and it still is saying permission denied.

Thanks

**Comment by FelixSchwarz** [comment]
jd4rider: let's try to use one deployment method only (wsgi or fastcgi) :-)

What do you mean by:
> It’s installed on root in Ubuntu

Do you mean that the data is located in /root? That is not a good place because that directory should be accessible only by root (and there might be other hard-coded restrictions to protect the dir and/or the root account, e.g. SELinux).

I'd recommend using something like /var/www or something like /srv/mediadrop. Then run MediaDrop as a regular user (e.g. "mediadrop", "website", ...). Ensure that that user can access the directory.

Please also show the relevant parts of your Apache config.  Which distro do you use?

**Comment by FelixSchwarz** [comment]
closing as there the original reporter did add additional information. I hope you figured it out by now. Feel free to reopen this ticket if you still experience problems.
